### ISSUE TITLE
Approving posts through edit menu does not actually approve posts

### ISSUE THREAD

**Issue by pcorey** [AdmitHub/Telescope#9] opened 2015-10-06 19:58 UTC
The workaround is the manually click the "approve" button on the post.

**Comment by yourcelf** [comment] 2015-10-09 01:01
Which is the "edit menu" -- is that the autoform rendered in the body of the "Edit" view?

**Comment by pcorey** [comment] 2015-10-09 02:20
Hey sorry Charlie,

I was writing this mostly as a note to myself.

Yes, the edit menu I'm talking about it the autoform you see in the edit view.  For example, https://college.admithub.com/posts/bhQTAC3H7y6HFTCew/edit

You can set posts to "approved" here, which apparently isn't correctly updating their status?

**Comment by yourcelf** [comment] 2015-10-09 03:59
Hmm... couldn't reproduce there.  I was able to toggle that particular post to "pending" and then to "approved" via the autoform, and it worked as expected.

**Comment by pcorey** [comment] 2015-10-09 23:54
@dp33 are you still having issues with this?

If you're still having issues with posts not becoming approved, what's your exact workflow when it comes to posts? How can we recreate it?

**Comment by dp33** [comment] 2015-10-10 00:56
The issue was that an approved post would only appear in the forum scroll if it was approved with the "approve" button beneath the vote up, edit, share, responses boxes.

If I clicked "edit" and then changed status from "pending" to "approved," the post wasn't displaying in the forum scroll; it seemed to be invisible.

**Comment by dp33** [comment] 2015-10-10 01:08
I just tested this again, and it seems to still be an issue. 

However, the issue seems to disappear once the "approved" button is clicked one time. After that, the initially faulty edit function works fine to switch from pending to approved and back again.

**Comment by pcorey** [comment] 2015-10-10 01:11
Cool, thanks Dan.

**Comment by yourcelf** [comment] 2015-10-21 15:45
OK, I found the part that's at fault here.  It looks like it's been fixed in upstream v0.25.2+ (we're currently on v0.24.0).  I'm going to suggest that we ignore this for now (just remember to approve via the "approve" button), and when we do the upgrade to v0.25+ this ought to be fixed.

v0.25 has some sizable breaking changes so it'll take a little doing to get ourselves updated for it.

**Closed as completed** 2016-03-22 20:26 UTC
Labels: bug
